# encoding: utf-8
USER_TAB = "Usuários"
USER_MANDATORY = [0, 5]
TEAM_TAB = "Times"
TEAM_MANDATORY = [0, 4]
USER_X_TEAM_TAB = "UsuárioxTime"
USER_X_TEAM_MANDATORY = [0, 1]
CYCLE_TAB = "Ciclo"
CYCLE_MANDATORY = [0, 1, 2, 3, 4]
OBJECTIVE_TAB = "Objetivos"
OBJECTIVE_MANDATORY = [0, 1, 2, 3]
KEY_RESULTS_TAB = "Resultados-chave"
KEY_RESULTS_MANDATORY = [0, 2, 3, 4, 5, 6, 7, 8]

VALID_TABS = [USER_TAB, TEAM_TAB, USER_X_TEAM_TAB, CYCLE_TAB, OBJECTIVE_TAB, KEY_RESULTS_TAB]